### ISSUE TITLE
crate_view (tm) errors on snotpenn01

### ISSUE THREAD

**Issue by bonventre** [mastbaum/debugdb#35]
{"code":500,"error":"render_error","reason":"function raised error: (new TypeError(\"invalid 'in' operand crates[crate_id].slots[slot]\", \"\", 193)) \nstacktrace: ([object Object],[object Object])@:193\n((function (head, req) {start({code: 200, headers: {'Content-Type': \"text/html\"}});var title = \"CrateView\";var crates = [];for (var i = 0; i < 19; i++) {crates[i] = {slots: []};crates[i].crate_id = i.toString();for (var j = 0; j < 16; j++) {crates[i].slots[j] = {};crates[i].slots[j].slot = j.toString();}}var row;while ((row = getRow())) {var crate_id = row.value.config.crate_id;var slot = row.value.config.slot;if (\"row\" in crates[crate_id].slots[slot]) {if (row.value.created > crates[crate_id].slots[slot].row.value.created) {crates[crate_id].slots[slot].row = row;}} else {crates[crate_id].slots[slot].row = row;}}var content = templates.render(\"crate_view.html\", req, {rows: crates});if (req.client) {$(\"#content\").html(content);document.title = title;req.cookie = cookies.readBrowserCookies();document.cookies = cookies.readBrowserCookies();} else {return templates.render(\"base.html\", req, {content: content, title: title});}}),[object Object],[object Object])@:917\n([object Object],[object Object])@:0\nrunList(function (head, req) {var core = require(\"kanso/core\");var fn = require(\"lib/app\").lists.crateview;return core.runList(fn, head, req);},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:952\n(function (head, req) {var core = require(\"kanso/core\");var fn = require(\"lib/app\").lists.crateview;return core.runList(fn, head, req);},[object Object],[object Array])@/usr/local/share/couchdb/server/main.js:997\n(\"_design/debugdb\",[object Array],[object Array])@/usr/local/share/couchdb/server/main.js:1431\n()@/usr/local/share/couchdb/server/main.js:1474\n@/usr/local/share/couchdb/server/main.js:1485\n"}

**Comment by mastbaum** [comment]
this is caused a crate_id outside range [0,19] and/or slot outside range [0,16].

I'll make CrateView ignore out-of-range values, but you should do some bounds checking before you push.

**Comment by mastbaum** [comment]
closed by 23eafcdb625647e629c48bab2dd5e500237e47d3
