### ISSUE TITLE
Get Ttot Test

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#50]
ch 23 got 9999 back and the db maked it as green, should have been marked as a fail.

Document ID: 78ce8395c4bb75fe337c9c7e9db62cab
FEC ID: f10e

Thanks,
Cam

**Comment by mastbaum** [comment]
@bonventre

**Comment by bonventre** [comment]
fixed in b13b4671db096c526fa4afae6b732b2e77e8b540

**Comment by mastbaum** [comment]
fixed in pennsnoplus/penn_daq
