### ISSUE TITLE
Charge Injection Scan

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#51]
Charge Injection Scan
Fri Jan 13 11:24:46 2012

I checked the Charge Injection Scan, but no tested that ch 23 has failed hard with 0's and the PennDB marked it as good (Green)

Document ID: 78ce8395c4bb75fe337c9c7e9d95cf28

**Comment by mastbaum** [comment]
@bonventre

**Comment by bonventre** [comment]
fixed in commit 4c6e8b91bc64b97f92fc5401239090d0bd08371c

**Comment by mastbaum** [comment]
fixed in pennsnoplus/penn_daq
