### ISSUE TITLE
Fails Negative

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#56]
After running the final test, at the top it shows the overall status of the board, after running  it i got a gold board (everything green) and at the top left corner it still said "Failed" in red. (run Document ID: 639060d585c59d8ab8fd884598831fc4, Wed Feb 8 08:40:52 2012, FEC ID: f067)

**Comment by mastbaum** [comment]
yeah, richie and i were arguing about whether he or i should make this determination (final test should pass if all sub-tests fail).

this is a duplicate of issue #52, so closing -- keep an eye on that one.
