### ISSUE TITLE
See_refl

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#57]
when running see_refl at the end of the final_test, pulses on  Nhit 100 and 20 remain after the test is complete.  It will trigger in and out.

I tried:

1)mtc_init    =  still happening 
2)crate_init  -c 12 -s 4   =   still happening 
3)crate_init  -c 12 -s 4 -x -v   =   still happening 
4) sm_reset -c 12  =   still happening 
5)tryed all 3 buttons on the back of the XL3 ( was not sure witch one was the restart)  =   still happening 

It seemed after idealing for about 15 mins it went away on it own??

**Comment by mastbaum** [comment]
@bonventre
