### ISSUE TITLE
Recent Tests

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#58]
when looking at the data base in the center there is "Recent Tests", it is failing to update the lates test , it keeps showing find_noise, location = past, date = Invalid Date.

**Comment by mastbaum** [comment]
Yeah, that's Richie actually importing tests from the past.

On Fri, Feb 10, 2012 at 2:41 PM, 21esc12
reply@reply.github.com
wrote:

**Comment by mastbaum** [comment]
@bonventre

**Comment by bonventre** [comment]
sorry i'm using it for my own evil plans, will delete them in an hour
