### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#66]
When in penn_DB, if you click on "All test" and then "final_test" to see the history of a board your where working on it will give you this message "No tests found"?? is there a way to revisit these logs?

**Comment by mastbaum** [comment]
this works for me... @bonventre?

**Comment by bonventre** [comment]
works for me too - which test specifically are you clicking on?

**Comment by 21esc12** [comment]
I am using Mozilla (probably a older version), and the pennDB link i am using is "http://debugdb.snotpenn01.snolab.ca:5984/", is this the same link you are using ?

**Comment by 21esc12** [comment]
i was looking for F0C6 final Test, just wondering if it was a gold board because i am having a hard time running the final test on it.

**Comment by bonventre** [comment]
Is it crashing? I can see that you haven't been able to get past crate
cbal, would you like me to try?

On Tue, May 22, 2012 at 12:41 PM, 21esc12 <
reply@reply.github.com

**Comment by 21esc12** [comment]
Sure if you don't mind, everything is running and I have a board in slot 13
and 8.
yup its crashing or running into segmentation faults, it seems like it might
be a little less stable then before, or this my just have been a bad board
but it seems like I cant view the history of this board on penndb anymore,
slot 8 F0C6.

-----Original Message-----
From: Richie Bonventre
[mailto:reply+i-4694231-6256b66765ac5b00d2735e6a4acfbbdfd1daddea-1064918@rep
ly.github.com] 
Sent: Tuesday, May 22, 2012 12:44 PM
To: 21esc12
Subject: Re: [debugdb] No tests found (#66)

Is it crashing? I can see that you haven't been able to get past crate
cbal, would you like me to try?

On Tue, May 22, 2012 at 12:41 PM, 21esc12 <
reply@reply.github.com

> wrote:
> 
> i was looking for F0C6 final Test, just wondering if it was a gold board
> because i am having a hard time running the final test on it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mastbaum/debugdb/issues/66#issuecomment-5852071

---

**Comment by bonventre** [comment]
There was a bug fix I had forgotten to push to crag1. Updated everything
again, should work now. Don't know about the debugdb problems though, can
we get an up to date browser installed?

On Tue, May 22, 2012 at 12:50 PM, 21esc12 <
reply@reply.github.com

**Comment by 21esc12** [comment]
FireFox is updated to 10.0.4, this might be the problem as it still sends me
a message no test found, but on google chrome it works great ??.

I will try installing the newest version of firefox.

The test stand is working amazing ones again thanks for your help!

-----Original Message-----
From: Richie Bonventre
[mailto:reply+i-4694231-6256b66765ac5b00d2735e6a4acfbbdfd1daddea-1064918@rep
ly.github.com] 
Sent: Tuesday, May 22, 2012 1:06 PM
To: 21esc12
Subject: Re: [debugdb] No tests found (#66)

There was a bug fix I had forgotten to push to crag1. Updated everything
again, should work now. Don't know about the debugdb problems though, can
we get an up to date browser installed?

On Tue, May 22, 2012 at 12:50 PM, 21esc12 <
reply@reply.github.com

> wrote:
> 
> Sure if you don't mind, everything is running and I have a board in slot
> 13
> and 8.
> yup its crashing or running into segmentation faults, it seems like it
> might
> be a little less stable then before, or this my just have been a bad board
> but it seems like I cant view the history of this board on penndb anymore,
> slot 8 F0C6.
> 
> -----Original Message-----
> From: Richie Bonventre
> [mailto:
> reply+i-4694231-6256b66765ac5b00d2735e6a4acfbbdfd1daddea-1064918@rep
> ly.github.com]
> Sent: Tuesday, May 22, 2012 12:44 PM
> To: 21esc12
> Subject: Re: [debugdb] No tests found (#66)
> 
> Is it crashing? I can see that you haven't been able to get past crate
> cbal, would you like me to try?
> 
> On Tue, May 22, 2012 at 12:41 PM, 21esc12 <
> reply@reply.github.com
> 
> > wrote:
> > 
> > i was looking for F0C6 final Test, just wondering if it was a gold board
> > because i am having a hard time running the final test on it.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/mastbaum/debugdb/issues/66#issuecomment-5852071
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mastbaum/debugdb/issues/66#issuecomment-5852124
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mastbaum/debugdb/issues/66#issuecomment-5852294

---
