### ISSUE TITLE
final_test time ordering

### ISSUE THREAD

**Issue by 21esc12** [mastbaum/debugdb#67]
Just some things that would be nice, but not needed:

Could  the tests done in the full test be displayed in sequential order or displayed in a in the same order?, visually faster to compare a boards history. (right now when you view a final test the tests that where done are always in random order)

**Comment by mastbaum** [comment]
Whoa, yeah, they're supposed to be ordered by time. Thought I fixed that
already... oops! I'll get on it.
On May 24, 2012 11:43 AM, "21esc12" <
reply@reply.github.com>
wrote:

**Comment by mastbaum** [comment]
appears to be working now
