### ISSUE TITLE
too many tags

### ISSUE THREAD

**Issue by sscarf** [mastbaum/debugdb#68]
daughterboard d544 has a gold rating, but it is displayed as having no rating...it seems this is because it has too many tags

**Comment by mastbaum** [comment]
@bonventre possible?

**Comment by mastbaum** [comment]
d544 looks fine... closing unless i hear otherwise @bonventre @sscarf

**Comment by sscarf** [comment]
when d544 was gold, it was displaying "none" but now that it's bad, the
database is displaying it correctly

On Tue, Jul 10, 2012 at 9:13 AM, Andy Mastbaum <
reply@reply.github.com

**Comment by mastbaum** [comment]
i think this was closed by 89bd5f83d7156ec6507846723106e6cebbc5950b but we should keep an eye on it. @sscarf submit a new issue if it happens again.
