### ISSUE TITLE
date ordering

### ISSUE THREAD

**Issue by sscarf** [mastbaum/debugdb#70]
when updating the electronic tags with the info that exists on the paper tags, sometimes there is info that doesnt have a date -- currently, the dateless entries appear above the other entries -- it would be better if they appeared at the bottom, because they typically contain old and not very useful information

**Comment by mastbaum** [comment]
put an old date and they will appear at the bottom.

**Comment by mastbaum** [comment]
as of cabe2606bfff90ca6180d0cff99f8822cb2db9fd, entries with no date specified will be assumed to have been written on the day of america's declaration of independence from the british crown.
