### ISSUE TITLE
case-sensitivity

### ISSUE THREAD

**Issue by sscarf** [mastbaum/debugdb#72]
the database has d0b7 and D0B7 as different boards, but I don't think they should be -- also, after creating a new tag, it used to go to a page that allowed you to either go to that board's history or go to the master tag list; now, it just prompts you to create another new tag, which isn't helpful because we almost never make two consecutive tags for the same board

**Comment by mastbaum** [comment]
@bonventre will change all tags to be lowercase and use "f" for FECs instead of "m"

the second problem i'm fixing.

**Comment by bonventre** [comment]
changed, but it should also only let you post tags for board ids that make sense (auto change m to f and auto lower case). similarly if no date is input

**Comment by mastbaum** [comment]
closed by cabe2606bfff90ca6180d0cff99f8822cb2db9fd
