### ISSUE TITLE
board totals

### ISSUE THREAD

**Issue by bonventre** [mastbaum/debugdb#75]
somewhere should show total gold/silver/bad/unknown boards for both test and debugging status, + totals for location

**Comment by mastbaum** [comment]
main page? yeah?

**Comment by mastbaum** [comment]
mostly done in 72362bd66d85872741a41c9d4e6f688720b68bac, debugging status is coming.

**Comment by mastbaum** [comment]
closed by f29e35764579cb25a5129f9b41375943f473fdb2
